### ISSUE TITLE
2D Gaussian function doesn't converge for well-defined stars

### ISSUE THREAD

**Issue by pbrus** [majkelx/teda#2]
For some well-spread objects on images the 2D Gaussian function doesn't converge at all. It happens for a few cases (5-10%) and concerns not saturated stars. Please, note the value of the sky and fwhm.

![profile_fitting](https://user-images.githubusercontent.com/19304263/90688023-1aac4980-e26e-11ea-8c5a-44058b09d7f3.png)

The failed fitting triggers `RuntimeWarning: overflow encountered in exp` exception referencing to the code (`teda/fitting.py, line 46.`):

```python
val = c + a * np.exp(-((mu_x - xy[0])** 2 + (mu_y - xy[1])** 2) / (2 * sig2))
```
Increasing the `dtype` to `np.float128` for `np.exp` function doesn't solve the issue. Moreover, it affects the rest of code and may cause further problems - I'm not able to reproduce them every time.

**Comment by majkelx** [comment]
Could you please provide as with sample FITS file for this case.

**Comment by pbrus** [comment]
I sent a sample to your CAMK e-mail.

**Comment by majkelx** [comment]
Indeed, sometimes fitting goes wild and runs away from the proper minima in parameter space. 

I will try to curb it a bit.
